version: '3'

services:
  app:
    build: .
    image: scrapper
    volumes:
      - ./graphs:/app/graphs
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=example
      - MYSQL_DATABASE=scrap
      - URL=https://coinmarketcap.com/fr/
      - VERBOSE
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: scrap
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
