name: Check Docker

on: [push]

jobs:
  check-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du repository
        uses: actions/checkout@v2

      - name: Vérifier la présence de Docker
        run: docker -v

      - name: Build de l'image Docker
        run: docker build -t scrapper:latest .

      - name: Connexion à Docker Hub
        run: docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Taguer et pousser l'image Docker
        run: docker tag scrapper:latest ${{ secrets.DOCKER_LOGIN }}/scrapper:latest |
            docker push ${{ secrets.DOCKER_LOGIN }}/scrapper:latest
  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-push] # Attendez que le job de build et de push soit terminé
    steps:
      - name: Connexion SSH à la VM de production
        uses: appleboy/ssh-action@master
        with:
          host: 20.240.194.164
          username: ubuntu
          password: ${{ secrets.PROD_VM_PASSWORD }}
          script: |
            docker pull ${{ secrets.DOCKER_LOGIN }}/scrapper:latest
            docker stop scrapper-live
            docker rm scrapper-live
            docker run -d --name scrapper-live -p 80:80 ${{ secrets.DOCKER_LOGIN }}/scrapper:latest
