name: Check Docker Login

on: [push]

jobs:
  check-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du repository
        uses: actions/checkout@v2

      - name: Vérifier la présence de Docker
        run: docker -v

      
      - name: Connexion à Docker Hub
        run: docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin ${{ secrets.DOCKER_PASSWORD }}

   